"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import DashboardShell from "@/components/layout/DashboardShell";

interface DocumentDetail {
  id: string;
  title: string;
  type: string;
  status: string;
  createdAt: string;
  inputData: Record<string, string>;
  outputUrl: string | null;
  aiModel: string;
  version: number;
}

const TYPE_LABELS: Record<string, string> = {
  employment_contract: "Employment Contract",
  offer_letter: "Offer Letter",
  staff_handbook: "Staff Handbook",
  payslip: "Payslip",
  p45: "P45",
};

export default function DocumentDetailPage() {
  const params = useParams();
  const [doc, setDoc] = useState<DocumentDetail | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!params.id) return;
    fetch(`/api/documents/${params.id}`)
      .then((res) => (res.ok ? res.json() : null))
      .then((data) => setDoc(data))
      .catch(() => setDoc(null))
      .finally(() => setLoading(false));
  }, [params.id]);

  if (loading) return <p className="text-sm text-gray-500">Loading...</p>;
  if (!doc) return <p className="text-sm text-red-500">Document not found.</p>;

  return (
    <DashboardShell>
      <div className="max-w-3xl">
        <Link href="/documents" className="text-sm text-blue-600 hover:text-blue-500">
          ← Back to documents
        </Link>

        <div className="mt-4 rounded-xl border border-gray-200 bg-white p-8">
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{doc.title}</h1>
              <p className="mt-1 text-sm text-gray-500">
                {TYPE_LABELS[doc.type] || doc.type} · v{doc.version} ·{" "}
                {new Date(doc.createdAt).toLocaleDateString("en-GB", {
                  day: "numeric",
                  month: "long",
                  year: "numeric",
                })}
              </p>
            </div>
            <span className="rounded-full bg-green-100 px-3 py-1 text-xs font-medium text-green-700">
              {doc.status}
            </span>
          </div>

          {doc.outputUrl && (
            <a
              href={doc.outputUrl}
              className="mt-6 inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-500"
            >
              Download PDF
            </a>
          )}

          <div className="mt-8">
            <h2 className="mb-4 text-sm font-semibold text-gray-700 uppercase tracking-wide">
              Input Data
            </h2>
            <dl className="grid gap-3 sm:grid-cols-2">
              {Object.entries(doc.inputData || {}).map(([key, value]) => (
                <div key={key}>
                  <dt className="text-xs font-medium text-gray-500 uppercase">
                    {key.replace(/_/g, " ")}
                  </dt>
                  <dd className="mt-0.5 text-sm text-gray-900">{String(value)}</dd>
                </div>
              ))}
            </dl>
          </div>

          {doc.aiModel && (
            <p className="mt-6 text-xs text-gray-400">Generated by {doc.aiModel}</p>
          )}
        </div>
      </div>
    </DashboardShell>
  );
}
